### PR TITLE
PLC4X-174 Adjust restrictive regular expression.

### PR DESCRIPTION
**Pull request by splatch**

### CODE REVIEW

**Comment by JulianFeinauer** [comment]
Hey Lukasz, this should go to rel/0.6 branch, I guess, or?

**Comment by splatch** [comment]
I spotted this bug with bacnet ip driver on develop but sure, it can be backported to 0.6 branch too.

**Comment by JulianFeinauer** [comment]
@chrisdutz could you also have a look here. I thought we moved all this regex stuff to one central place (using java bultin classes). This approach would not allow us to parse path parameters, right?

**Comment by JulianFeinauer** [comment]
@splatch LGTM but I'm just a bit confused that the regex is there in the first place, so let me shortly check why that is than we can merge it : )
For rel/0.6 I can merge it asap.

**Comment by chrisdutz** [comment]
Well I split up the parts of the connection string ... the ip/hostname stuff should now be in the tcp and udp transport modules. Just can't immediately find it but in general the url is split up into {protocol}:{transport}://{transport-config}?{parameter-string}

**Comment by chrisdutz** [comment]
Aaahh ... yeah ... just had a look ... of course ... The patch is for the Transport ... so this is exactly the place where it has to be fixed.

**Comment by splatch** [comment]
Since I've got thumbs up, I've pushed changes to develop. I will pray for jenkins to pass the build. ;-)

**Pull request closed without merging**
