### PR TITLE
Remove support for var-args in plc4j

### PR DESCRIPTION
**Pull request by splatch**

### CODE REVIEW

**Comment by chrisdutz** [comment]
Checked it out, built it locally and ran the manual tests against my equipment. All worked fine. Also had a look at the changes in the drivers and liked what I saw.

**Review by chrisdutz — APPROVED** [review]
LGTM

**Comment by splatch** [comment]
Great, will rebase and push changes.

**Comment by chrisdutz** [comment]
I think if you rebase a branch that you already pushed, that's when you get these nasty github warnings ... I only rebase "develop" and merge all others ... but please ... don't merge before the build passes ;-)

**Comment by chrisdutz** [comment]
image

**Comment by splatch** [comment]
You push changes faster than CI completes jobs. :-)

**Pull request merged**
