### PR TITLE
fix(integrations/camel): Connection now established in doStart() of Producer/Consumer instead of constructors (#713)

### PR DESCRIPTION
**Pull request by SteinOv**
See [bug 713](https://github.com/apache/plc4x/issues/713)

### CODE REVIEW

**Comment by chrisdutz** [comment]
Hi,

thanks for this ... and sorry for not replying earlier. 
A few weeks ago we donated this component to the Apache Camel project as we thought it was better to keep it there.
So I guess we should probably be deleting this component in our repo and not to double-maintain it here.

If you would be so kind to submit this MR in the Apache camel repo, I would be happy to add a LGTM (Looks good to me) there.

Chris

**Comment by SteinOv** [comment]
Hi,

I created the pull request on the Camel project: [PR-8967](https://github.com/apache/camel/pull/8967).

Could you also take a look at [this feature request](https://github.com/apache/plc4x/issues/716)?

Thanks!

**Comment by sruehl** [comment]
@SteinOv & @chrisdutz guess we can close this then?

**Comment by SteinOv** [comment]
Yes, agreed. I'll close it.

**Pull request closed without merging**
