### PR TITLE
Update bit-io to newest version with OSGi support

### PR DESCRIPTION
**Pull request by cschneider**

### CODE REVIEW

**Comment by cschneider** [comment]
See https://github.com/jinahya/bit-io/pull/12

**Comment by JulianFeinauer** [comment]
@cschneider woudl you mind if I merge your change into my osgi branch and close the PR there, then?

**Comment by cschneider** [comment]
That ist fine

Julian <notifications@github.com> schrieb am So., 20. Okt. 2019, 14:11:

**Comment by JulianFeinauer** [comment]
Thank you very much for the support @cschneider will merge!

**Pull request merged**
