### PR TITLE
Ab eth station address parameter

### PR DESCRIPTION
**Pull request by vemmert**
Until now the station parameter, which is part of the DF1 block within the AB-ETH frame was defaulted to 8. It is now part of the connection string.

### CODE REVIEW

**Comment by vemmert** [comment]
Until now the station parameter, which is part of the DF1 block within the AB-ETH frame was defaulted to 8. It is now part of the connection string.

**Comment by JulianFeinauer** [comment]
@vemmert looks good to me too : )
It would be nice to squash those commints into one to have fewer noise in the history (git rebase -i origin/develop). Is that okay for you?

**Comment by vemmert** [comment]
> It would be nice to squash those commints into one to have fewer noise in the history (git rebase -i origin/develop). Is that okay for you?

Done.

**Comment by JulianFeinauer** [comment]
thanks!

**Pull request merged**
