### PR TITLE
Feature: Add connection option to connect with CPs

### PR DESCRIPTION
**Pull request by JulianFeinauer**

### CODE REVIEW

**Comment by splatch** [comment]
@JulianFeinauer Does it apply to later releases? If so, can we ensure its available there too?

**Comment by chrisdutz** [comment]
I would assume the same should apply also for the newer versions ... we should double-check

**Comment by chrisdutz** [comment]
We don't have a "device-group" setting in the newer versions ... and probably, if we added it, we should add variants for local and remote "device-group" ... "local-device-group" defaulting to PG_OR_PC and "remote-device-group" defaulting to OTHERS.

**Comment by JulianFeinauer** [comment]
Indeed, good point. We came across this when connecting to an old s7 300 with a Communication processor. I don't know the theory well enough but it seems in this case we do not need rack but slot and device group setting

**Pull request merged**
