### PR TITLE
Attempt to stabilize OPC UA unit tests

### PR DESCRIPTION
**Pull request by splatch**
Related to #1764.

### CODE REVIEW

**Comment by splatch** [comment]
@chrisdutz Looks like tests after above changes are better. Would you risk merging this to see how it will go with Jenkins? Can you give it a try on Mac/Parallels?

**Comment by chrisdutz** [comment]
How about manually re-running the tests for 4-5 times ... if they remain unflaky, please merge them ... if they remain flaky, please don't enable them. I'd really like to have our build in a form again, that we can trust it and not blindly click "rerun failed" for 2-3 times before we start looking if it's really a problem.

**Comment by chrisdutz** [comment]
Hmmm ... odd ... I had that error a few days ago ... as if Java forgot it's own options ... maybe just run again later.

**Comment by splatch** [comment]
The good thing is - build didn't fail due to opcua :-)

**Comment by splatch** [comment]
@chrisdutz Ping - looks like tests are a bit better on github, there are fewer failures coming from OPC-UA. Would you risk merging them now?

**Comment by chrisdutz** [comment]
Well ... let's see ... if they start randomly failing the build there, I'll deactivate them again ... so let's consider them "on probation" ;-)

**Comment by splatch** [comment]
I see chunk tests are failing again, will have a closer look on them. Milo seems to be fine with testcontainers and randomized network port.

**Pull request merged**
