### PR TITLE
added strtok_s define for windows

### PR DESCRIPTION
**Pull request by thomas169**

### CODE REVIEW

**Review by hutcheb — APPROVED** [review]

**Comment by chrisdutz** [comment]
So this fixes a problem using the code on non-windows system? Had to do a little research to what this PR is about. A bit of context would have been helpful ;-)

**Comment by thomas169** [comment]
Apologies, (but go easy was my first ever PR :) ). Yes allows hello world s7 to link without error on Linux

**Comment by chrisdutz** [comment]
No worries ... I was just confused as you wrote what you did, but not why ;-) 

We're always happy about getting new PRs from new folks ... so first off all: Welcome :-)

This C stuff is so fragile, that I'm a bit nervous to just merge stuff.

But it seems you added the define to windows in order to be able to use the linux variant on windows and linux, right?

Chris

**Comment by thomas169** [comment]
Thanks, hopefully I will help out a bit more, certainly will if we start using PLC4x.

Yes, its effectively 0 change on windows (after preprocessor anyway) and a small fix on Linux

**Comment by chrisdutz** [comment]
And ... I'm definitely no C-Pro ... so expect other "things" in there ... I'd be happy, if someone with experience would help get that thing into shape :-)

Going to merge the PR now ... thanks for contributing. 

And if you haven't so-far, please subscribe to our mailinglist dev@plc4x.apache.org (by sending an empty email to dev-subscribe@plc4x.apache.org) :-)

**Pull request merged**
