### PR TITLE
PLC4X-304 Improve status code mappings for OPC UA.

### PR DESCRIPTION
**Pull request by splatch**
Improved mapping for error codes. Turns out that we can detect security error using Milo apis. More over status code comparison should use `.isGood()` methods cause these are results of comparison at bit mask level.

### CODE REVIEW

**Comment by GlennZeng** [comment]
Thank you for your dedication! I want to ask if there is an opcua code case. I want to refer to it. I searched a lot and couldn't find it. I saw that there seems to be no place to enter the opcua account password in your connection code. What's the matter?

**Comment by splatch** [comment]
Hey Glen,
Currently the high level API of PLC4X does specify a concept of credentials, but these as far as I know are not being used by any of drivers. Even for OPC UA where there is a support for various kinds of authentication it is not being utilized.

Have a look on https://github.com/apache/plc4x/blob/v0.8.0/plc4j/drivers/opcua/src/main/java/org/apache/plc4x/java/opcua/connection/OpcuaTcpPlcConnection.java#L343L349 - this is place where Eclipse Milo client is being initialized. It should rely on non-anonymous identity provider.
I believe @hutcheb will know best how future handling of this will look a like.

**Comment by beyondyinjl2** [comment]
Is there a golang opcua driver?

**Comment by ottlukas** [comment]
> Is there a golang opcua driver?

Not yet

**Comment by GlennZeng** [comment]
Thanks for your reply! I would also like to ask, what protocols does golang currently support? What protocols does Java temporarily support?

**Comment by ottlukas** [comment]
> Thanks for your reply! I would also like to ask, what protocols does golang currently support? What protocols does Java temporarily support?

https://plc4x.apache.org/users/protocols/index.html see our Table here -> Java supports most of the protocols -> Golang -> KNX, S7 and Modbus . C -> S7

**Comment by hutcheb** [comment]
> Thank you for your dedication! I want to ask if there is an opcua code case. I want to refer to it. I searched a lot and couldn't find it. I saw that there seems to be no place to enter the opcua account password in your connection code. What's the matter?

I have merged a major update for the OPCUA protocol into develop, it should allow you to specify a username and password as part of the connection string e.g. opcua:tcp://127.0.0.1:4840/node?username=fred;password=fredspassword

For the status codes, this should have all of them available in opcua,
https://github.com/OPCFoundation/UA-Nodeset/blob/v1.04/Schema/StatusCode.csv
I'll double check how it is now handled, but if you could take a look at the update and comment it woulld be very helpful.

**Comment by splatch** [comment]
Given that we got brand new and fresh OPC UA I'll close this PR. Above code can be used as an patch for 0.8 release.

**Pull request closed without merging**
